"""initial schema

Revision ID: e25f64388707
Revises: 
Create Date: 2026-06-20 04:00:54.872506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25f64388707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.Enum('HARTA', 'PIUTANG', 'INVENTARIS', 'UTANG', 'MODAL', 'PENDAPATAN', 'BIAYA', name='kategoriakun'), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', name='uq_akun_kode')
    )
    op.create_table('departemen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('angkatan', sa.String(length=10), nullable=False),
    sa.Column('tingkat', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelompok_calon_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahun_buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('tahun_buku', sa.String(length=20), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('awalan_kuitansi', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'TUTUP', name='statustahunbuku'), nullable=False),
    sa.Column('akun_retained_earning_id', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['akun_retained_earning_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departemen_id', 'tahun_buku', name='uq_departemen_tahun_buku')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tingkat', sa.Enum('ADMIN', 'MANAJER', 'STAF', name='tingkatpengguna'), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('login_terakhir', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabel', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('aksi', sa.Enum('EDIT', 'HAPUS', name='aksiaudit'), nullable=False),
    sa.Column('data_lama', sa.JSON(), nullable=True),
    sa.Column('data_baru', sa.JSON(), nullable=True),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calon_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_registrasi', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kelompok_id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('proses', sa.String(length=50), nullable=True),
    sa.Column('hp', sa.String(length=30), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('tanggal_daftar', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.ForeignKeyConstraint(['kelompok_id'], ['kelompok_calon_siswa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_registrasi')
    )
    op.create_table('jurnal_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_jurnal', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('tahun_buku_id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('sumber_modul', sa.Enum('PENERIMAAN', 'PENGELUARAN', 'JURNAL_UMUM', 'TUTUP_BUKU', name='sumbermodul'), nullable=False),
    sa.Column('sumber_id', sa.Integer(), nullable=True),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'DIBATALKAN', name='statusjurnal'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tahun_buku_id'], ['tahun_buku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_jurnal')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.String(length=30), nullable=True),
    sa.Column('telepon', sa.String(length=30), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('AKTIF', 'LULUS', 'KELUAR', name='statussiswa'), nullable=False),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('jurnal_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurnal_header_id', sa.Integer(), nullable=False),
    sa.Column('akun_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kredit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['akun_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['jurnal_header_id'], ['jurnal_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurnal_detail')
    op.drop_table('siswa')
    op.drop_table('jurnal_header')
    op.drop_table('calon_siswa')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('tahun_buku')
    op.drop_table('kelompok_calon_siswa')
    op.drop_table('kelas')
    op.drop_table('departemen')
    op.drop_table('akun')
    # ### end Alembic commands ###
