"""tambah modul inventory

Revision ID: 13ee0d75e6d5
Revises: 7f2e3ab9c7f8
Create Date: 2026-06-21 07:16:45.892806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ee0d75e6d5'
down_revision = '7f2e3ab9c7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['group_barang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', name='uq_group_barang_kode')
    )
    op.create_table('barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('satuan', sa.String(length=20), nullable=False),
    sa.Column('stok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_barang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', name='uq_barang_kode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    op.drop_table('group_barang')
    # ### end Alembic commands ###
