"""tambah modul penerimaan

Revision ID: 39ebca058fb7
Revises: e25f64388707
Create Date: 2026-06-21 06:10:51.840045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ebca058fb7'
down_revision = 'e25f64388707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('akun_piutang_id', sa.Integer(), nullable=False),
    sa.Column('akun_pendapatan_id', sa.Integer(), nullable=False),
    sa.Column('nominal_default', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['akun_pendapatan_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['akun_piutang_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_tagihan', sa.String(length=30), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('jenis_pembayaran_id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('tahun_buku_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah_tagihan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sisa', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('BELUM_LUNAS', 'LUNAS', 'DIBATALKAN', name='statustagihan'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('jurnal_header_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.ForeignKeyConstraint(['jenis_pembayaran_id'], ['jenis_pembayaran.id'], ),
    sa.ForeignKeyConstraint(['jurnal_header_id'], ['jurnal_header.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['tahun_buku_id'], ['tahun_buku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_tagihan')
    )
    op.create_table('pembayaran_tagihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagihan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah_bayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('akun_kas_id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'DIBATALKAN', name='statuspembayaran'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('jurnal_header_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['akun_kas_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['jurnal_header_id'], ['jurnal_header.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tagihan_id'], ['tagihan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembayaran_tagihan')
    op.drop_table('tagihan')
    op.drop_table('jenis_pembayaran')
    # ### end Alembic commands ###
