"""tambah modul pengeluaran

Revision ID: 7f2e3ab9c7f8
Revises: 831b724d9486
Create Date: 2026-06-21 06:56:13.715604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2e3ab9c7f8'
down_revision = '831b724d9486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_pengeluaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('akun_kas_id', sa.Integer(), nullable=False),
    sa.Column('akun_biaya_id', sa.Integer(), nullable=False),
    sa.Column('nominal_default', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['akun_biaya_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['akun_kas_id'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengeluaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_kuitansi', sa.String(length=30), nullable=False),
    sa.Column('jenis_pengeluaran_id', sa.Integer(), nullable=False),
    sa.Column('departemen_id', sa.Integer(), nullable=False),
    sa.Column('tahun_buku_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'DIBATALKAN', name='statuspengeluaran'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('jurnal_header_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departemen_id'], ['departemen.id'], ),
    sa.ForeignKeyConstraint(['jenis_pengeluaran_id'], ['jenis_pengeluaran.id'], ),
    sa.ForeignKeyConstraint(['jurnal_header_id'], ['jurnal_header.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tahun_buku_id'], ['tahun_buku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_buku_id', 'no_kuitansi', name='uq_pengeluaran_tahun_buku_no_kuitansi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengeluaran')
    op.drop_table('jenis_pengeluaran')
    # ### end Alembic commands ###
